-- Drop existing embedding column if it exists
ALTER TABLE job_listings DROP COLUMN IF EXISTS embedding;

-- Add new embedding column with proper vector type
ALTER TABLE job_listings ADD COLUMN embedding vector(1536);

-- Create an index on the embedding column for faster similarity search
CREATE INDEX IF NOT EXISTS job_listings_embedding_idx ON job_listings USING ivfflat (embedding vector_cosine_ops);

-- Create a function to generate embeddings
CREATE OR REPLACE FUNCTION generate_job_embedding()
RETURNS TRIGGER AS $$
BEGIN
    -- The embedding will be generated by the application layer
    -- This function is just a placeholder for future use
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Create a trigger to handle embedding generation
DROP TRIGGER IF EXISTS generate_job_embedding_trigger ON job_listings;
CREATE TRIGGER generate_job_embedding_trigger
    BEFORE INSERT OR UPDATE ON job_listings
    FOR EACH ROW
    EXECUTE FUNCTION generate_job_embedding(); 